// src/lib/copy.ts
// Locked copy from DRIVEX storyboard. Edit only via PR `chore: update copy`.

export const panelCopy = {
  W01_MIRA: {
    number: '01',
    eyebrow: 'MULTILINGUAL INTELLIGENT REAL-TIME AGENT',
    title: 'MIRA',
    body: 'An autonomous voice agent that instantly calls sales leads, conducts natural conversations in five languages, and securely pushes structured qualification data directly to the CRM.',
    metric: { label: 'RESPONSE TIME', value: '482ms' },
    chips: [
      'VOBIZ',
      'PIPECAT',
      'WEBSOCKETS',
      'ASR/TTS',
      'LLM',
      'ZOHO CRM',
      'WHATSAPP',
    ],
    trail: ['NOISE', 'SIGNAL', 'UNDERSTANDING'],
    languages: [
      'ENGLISH',
      'हिंदी',
      'தமிழ்',
      'ಕನ್ನಡ',
      'తెలుగు',
    ],
  },
  W02_AIDEN: {
    number: '02',
    eyebrow: 'AI-DRIVEN ENGAGEMENT ANALYTICS',
    title: 'AIDEN',
    body: 'An analytics engine that transforms raw sales calls into actionable coaching metrics by automatically grading agents against compliance and objection handling standards.',
    chips: [
      'SARVAM DIARIZATION',
      'HUME PROSODY',
      'SOP SCORING',
      'GEMINI',
      'POST-CALL INTEL',
      'ZOHO CRM',
    ],
    trail: ['CONVERSATIONS', 'INSIGHTS', 'ACTION'],
    metricsAxes: ['Emotion', 'Intent Cluster', 'SOP Adherence', 'Engagement Score'],
  },
  W03_VANGUARD: {
    number: '03',
    eyebrow: 'AUTONOMOUS WEB TESTING AGENT',
    title: 'VANGUARD',
    body: 'An autonomous testing agent that visually crawls web applications to catch regressions, accessibility violations, and network failures before bad code ships to production.',
    chips: ['PLAYWRIGHT', 'MCP TOOLS', 'TEMPLATE CLUSTERS', 'DOM CHECKS', 'A11Y SNAPSHOTS'],
    trail: ['EXPLORE', 'TEST', 'ADAPT', 'VALIDATE'],
    callouts: [
      { label: 'ISSUE DETECTED', sub: 'Element Overlap', tone: 'red' as const },
      { label: 'SELF HEALING', sub: 'Re-attempting…', tone: 'amber' as const },
      { label: 'TEST PASSED', sub: 'All Good', tone: 'green' as const },
    ],
  },
  W04_INSPECTION: {
    number: '04',
    eyebrow: 'AI POWERED VEHICLE INSPECTION',
    title: 'AI INSPECTION',
    body: 'A computer vision pipeline that analyzes live camera feeds to instantly detect vehicle defects, aggressively standardizing quality control operations on the showroom floor.',
    chips: ['YOLOV8', 'RTSP STREAMS', 'FRAME WATCHDOG', 'EVIDENCE CAPTURE', 'VERONICA API'],
    trail: ['SCAN', 'DETECT', 'ANALYZE', 'ASSURE'],
    layers: ['STRUCTURE', 'MECHANICAL', 'ELECTRICAL', 'COSMETIC', 'TYRES & WHEELS'],
  },
  W05_WAVEFIELD: {
    number: '05',
    eyebrow: 'WAVE FIELD LLM RESEARCH',
    title: 'WAVE FIELD',
    body: 'Fundamental AI research proposing a causal wave kernel to replace standard attention, mathematically targeting O(n log n) scaling for massive text contexts.',
    chips: ['RESEARCH', 'FOURIER KERNELS', 'CONTENT GATES', 'O(N LOG N) TARGET', 'LONG CONTEXT'],
    trail: ['RETHINK', 'RESEARCH', 'REDUCE COMPLEXITY'],
    comparison: {
      left: {
        label: 'STANDARD ATTENTION',
        complexity: 'O(n²)',
        metric: '1M tokens',
        sub: '~200,000× SLOWER',
      },
      right: {
        label: 'WAVE FIELD ATTENTION',
        complexity: 'O(n log n)',
        metric: '1M tokens',
        sub: 'STABLE & EFFICIENT',
      },
    },
  },
  W06_EMI: {
    number: '06',
    eyebrow: 'EMI SHIELDING DESIGNER & COMPUTATIONAL PHYSICS ENGINE',
    title: 'EMI ENGINE',
    body: 'A computational physics engine that simulates electromagnetic shielding effectiveness, automatically recommending optimal material and thickness configurations for engineers.',
    chips: ['SCHELKUNOFF', 'TRANSFER MATRIX', 'GRAIN EFFECTS', 'MATERIAL SEARCH', 'VALIDATION'],
    trail: ['MODEL', 'SIMULATE', 'PREDICT', 'PROTECT'],
    sweepRange: '100 kHz – 10 GHz',
  },
  W07_FORMULA: {
    number: '07',
    eyebrow: 'FORMULA MANIPAL',
    title: 'FORMULA MANIPAL',
    body: 'Hands-on race engineering and vehicle manufacturing, specializing in custom carbon composites, drivetrain assembly, and team operations for a championship-winning formula car.',
    chips: [
      'ENGINE ASSEMBLY',
      'TRANSMISSION',
      '3K TWILL CARBON',
      'VACUUM INFUSION',
      'INR 60L SPONSORS',
    ],
    trail: ['BUILD', 'COMPOSITES', 'FUND', 'COMPETE'],
    legend: ['MANUFACTURING', 'CARBON BODYWORK', 'OPERATIONS', 'COMPETITION'],
  },
  W08_ABOUT: {
    number: '08',
    eyebrow: 'ABOUT ME',
    title: 'SYSTEMS-FIRST ENGINEER',
    body: 'I build the layer between ambitious AI ideas and operating reality: backends, ' +
      'agents, data flows, product surfaces and the tradeoffs that keep them alive.',
    chips: [
      'AI SYSTEMS & PRODUCT',
      'FULL STACK',
      'BACKEND ARCHITECTURE',
      'PRODUCT JUDGMENT',
      'RESEARCH DEPTH',
      'OPERATIONS',
    ],
    trail: ['FIND THE BOTTLENECK', 'BUILD THE SYSTEM', 'DEFEND THE TRADEOFF'],
    skills: [
      'AI SYSTEMS & PRODUCT',
      'BACKEND ENGINEERING',
      'FRONTEND EXECUTION',
      'RESEARCH',
      'PHYSICS & SIMULATION',
      'PRODUCT THINKING',
      'REAL WORLD OPS',
    ],
  },
  W09_CONNECT: {
    number: '09',
    eyebrow: "LET'S CONNECT",
    title: 'SEND THE SIGNAL',
    body: 'Best fit: teams building AI products where correctness, latency and ownership matter.',
    trail: ['EMAIL FIRST', 'TECHNICAL SCREEN', 'SYSTEMS WALKTHROUGH'],
    links: [
      {
        label: 'LINKEDIN',
        icon: 'linkedin',
        href: 'https://linkedin.com/in/danush-arun-5aa762267',
      },
      { label: 'GITHUB', icon: 'github', href: 'https://github.com/DanushArun' },
      { label: 'EMAIL', icon: 'mail', href: 'mailto:danusharun999@gmail.com' },
    ],
  },
} as const;

export type PanelCopy = typeof panelCopy;
