import { SUPERCLUSTER_CHAPTER_COLORS } from './constants';
import { SUPERCLUSTER_FINAL_CHAPTERS } from './final-chapters';
import type { SuperclusterChapter, SuperclusterDot } from './types';
import { SUPERCLUSTER_TAIL_CHAPTERS } from './tail-chapters';

function dot(config: SuperclusterDot): SuperclusterDot {
  return config;
}

function chapter(config: SuperclusterChapter): SuperclusterChapter {
  if (config.dots.length !== config.dotCount) {
    throw new Error(`Dot count mismatch for ${config.id}`);
  }
  return config;
}

const SUPERCLUSTER_HEAD_CHAPTERS: readonly SuperclusterChapter[] = [
  chapter({
    catalogueLabel: 'MIRA CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.MIRA,
    complexity: 'high',
    dotCount: 8,
    id: 'MIRA',
    mostDemandingDotId: 'voice-intake',
    particlePoolPercent: 15,
    title: 'Multilingual Intelligent Real-time Agent',
    dots: [
      dot({
        answer: 'Production voice agent',
        behaviors: ['pulse', 'condense'],
        body: 'Production outbound voice AI for sales-call conversion.',
        camera: 'Wide arrival on MIRA density node, center-right and slightly elevated.',
        id: 'production-system',
        label: '1/8',
        question: 'Did this ship?',
        tags: ['FASTAPI', 'KUBERNETES', 'PIPECAT'],
        title: 'Production System',
        visual: 'Gold node pulses twice, then tightens without forming a full artifact.',
      }),
      dot({
        answer: 'Sub-100ms',
        behaviors: ['route'],
        body: 'First response dropped from 7s to under 500ms across 4 iterations.',
        camera: 'Moves closer with slight downward tilt to show arc contraction.',
        id: 'latency-collapse',
        label: '2/8',
        question: 'How fast?',
        tags: ['REAL-TIME', 'STREAMING ASR', 'FASTAPI'],
        title: 'Latency Collapse',
        visual: 'Long curved latency arcs contract into tight direct connection lines.',
      }),
      dot({
        answer: '5 Indian languages',
        behaviors: ['route'],
        body: 'EN, HI, TA, KN, TE all running in parallel, live in production.',
        camera: 'Rotates 30 degrees clockwise to reveal band depth and separation.',
        id: 'language-bands',
        label: '3/8',
        question: 'Which languages?',
        tags: ['EN', 'HI', 'TA', 'KN', 'TE'],
        title: 'Language Bands',
        visual: 'Five colored orbital signal streams form around the MIRA core.',
      }),
      dot({
        answer: 'VAD -> ASR -> Language',
        behaviors: ['route'],
        body: 'Three-stage intake pipeline with sub-100ms target per stage.',
        camera: 'Slightly above-left view frames the incoming stream and fork.',
        id: 'voice-intake',
        label: '4/8',
        question: 'How does voice enter?',
        tags: ['SARVAM AI', 'STREAMING ASR', 'VAD'],
        title: 'Voice Intake',
        visual: 'Incoming call particles fork into VAD, ASR, and language streams.',
      }),
      dot({
        answer: 'Pipecat orchestration',
        behaviors: ['condense', 'pulse'],
        body: 'Model handoffs, turn management, and agentic state routing.',
        camera: 'Center-facing frame with routing core in focal center.',
        id: 'orchestration-core',
        label: '5/8',
        question: 'Who coordinates it?',
        tags: ['PIPECAT', 'REDIS', 'CELERY'],
        title: 'Orchestration Core',
        visual: 'Split streams converge into a dense core with pulsing handoff nodes.',
      }),
      dot({
        answer: 'Structured intent',
        behaviors: ['condense'],
        body: 'Confidence score, intent classification, and date extraction per lead.',
        camera: 'Shifts right to frame the core and three output clusters.',
        id: 'post-call-output',
        label: '6/8',
        question: 'What does it produce?',
        tags: ['STRUCTURED OUTPUTS', 'ZOHO CRM', 'DJANGO'],
        title: 'Post-Call Output',
        visual: 'Output particles compress into intent, confidence, and date clusters.',
      }),
      dot({
        answer: 'CRM + WhatsApp',
        behaviors: ['route'],
        body: 'Zoho CRM sync and auto-group WhatsApp creation with bot coordination.',
        camera: 'Pulls back to include outgoing infrastructure filaments.',
        id: 'ops-loop',
        label: '7/8',
        question: 'Where does it go?',
        tags: ['ZOHO CRM', 'WHATSAPP API', 'FASTAPI'],
        title: 'Ops Loop',
        visual: 'CRM and WhatsApp filaments depart into distant supercluster nodes.',
      }),
      dot({
        answer: 'Sole architect',
        behaviors: ['pulse', 'shear', 'rejoin'],
        body: 'Architecture, speech pipeline, orchestration, CRM sync, and bot.',
        camera: 'Chapter climax, then travel toward AIDEN.',
        id: 'ownership',
        label: '8/8',
        question: 'Who built it?',
        tags: ['END-TO-END', 'PRODUCTION', 'DEPLOYED'],
        title: 'Ownership',
        visual: 'Entire artifact brightens, pulses from core, then dissolves last at bands.',
      }),
    ],
  }),
  chapter({
    catalogueLabel: 'AIDEN CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.AIDEN,
    complexity: 'high',
    dotCount: 6,
    id: 'AIDEN',
    mostDemandingDotId: 'diarization',
    particlePoolPercent: 12,
    title: 'AI-Driven ENgagement Analytics',
    dots: [
      dot({
        answer: 'Call intelligence',
        behaviors: ['condense', 'route'],
        body: 'Full-stack analytics platform for sales management call visibility.',
        camera: 'Side-elevation view with two bands running left to right.',
        id: 'speaker-separation',
        label: '1/6',
        question: 'What is AIDEN?',
        tags: ['REACT', 'DJANGO', 'KUBERNETES'],
        title: 'Speaker Separation',
        visual: 'Agent and customer particles separate into two horizontal bands.',
      }),
      dot({
        answer: 'Speaker diarization',
        behaviors: ['condense'],
        body: 'Every utterance attributed and every speaker separated across calls.',
        camera: 'Oblique 30 degree front view reveals helix depth.',
        id: 'diarization',
        label: '2/6',
        question: 'Can you tell them apart?',
        tags: ['DIARIZATION', 'TRANSCRIPTION', 'PARALINGUISTICS'],
        title: 'Diarization',
        visual: 'Two bands braid into a cyan and amber conversation helix.',
      }),
      dot({
        answer: '8 SOP dimensions',
        behaviors: ['pulse'],
        body: 'Greeting, discovery, pitch, objection handling, close, and compliance.',
        camera: 'Slight overhead tilt shows helix and all scoring planes.',
        id: 'sop-scoring',
        label: '3/6',
        question: 'How is quality measured?',
        tags: ['LLM SCORING', 'SOP', 'ANALYTICS'],
        title: 'SOP Scoring',
        visual: 'Eight semi-transparent scoring planes slice through the helix.',
      }),
      dot({
        answer: 'Parallel LLM analysis',
        behaviors: ['route'],
        body: 'Multiple models run across emotion, content, and SOP compliance.',
        camera: 'Pulls back to show helix plus three parallel tracks.',
        id: 'parallel-llm',
        label: '4/6',
        question: 'How deep is the analysis?',
        tags: ['PARALLEL LLM', 'HUME AI', 'STRUCTURED OUTPUTS'],
        title: 'Parallel LLM Tracks',
        visual: 'Three analysis tracks split from the helix and rejoin at insight nodes.',
      }),
      dot({
        answer: 'Zoho CRM embedded',
        behaviors: ['condense'],
        body: 'React dashboard embedded inside Zoho CRM for managers.',
        camera: 'Shifts right to frame helix, bridge, and dashboard grid.',
        id: 'dashboard-surface',
        label: '5/6',
        question: 'Where does it surface?',
        tags: ['REACT', 'ZOHO CRM', 'EMBEDDED'],
        title: 'Dashboard Surface',
        visual: 'Output particles organize into an angled layered dashboard grid.',
      }),
      dot({
        answer: 'K8s + E2E coverage',
        behaviors: ['condense', 'pulse', 'shear', 'rejoin'],
        body: 'Production Kubernetes deployment with full end-to-end test coverage.',
        camera: 'Wide hold before travel toward VANGUARD.',
        id: 'reliability',
        label: '6/6',
        question: 'Does it hold?',
        tags: ['KUBERNETES', 'PLAYWRIGHT', 'E2E'],
        title: 'Reliability',
        visual: 'Sparse green-gold guardrail encloses helix, tracks, and dashboard.',
      }),
    ],
  }),
];

export const SUPERCLUSTER_CHAPTERS: readonly SuperclusterChapter[] = [
  ...SUPERCLUSTER_HEAD_CHAPTERS,
  ...SUPERCLUSTER_TAIL_CHAPTERS,
  ...SUPERCLUSTER_FINAL_CHAPTERS,
];
