import { SUPERCLUSTER_CHAPTER_COLORS } from './constants';
import { SUPERCLUSTER_FINAL_CHAPTERS } from './final-chapters';
import type { SuperclusterChapter, SuperclusterDot } from './types';
import { SUPERCLUSTER_TAIL_CHAPTERS } from './tail-chapters';

function dot(config: SuperclusterDot): SuperclusterDot {
  return config;
}

function chapter(config: SuperclusterChapter): SuperclusterChapter {
  if (config.dots.length !== config.dotCount) {
    throw new Error(`Dot count mismatch for ${config.id}`);
  }
  return config;
}

const SUPERCLUSTER_HEAD_CHAPTERS: readonly SuperclusterChapter[] = [
  chapter({
    catalogueLabel: 'MIRA CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.MIRA,
    complexity: 'high',
    dotCount: 7,
    id: 'MIRA',
    mostDemandingDotId: 'challenge',
    particlePoolPercent: 15,
    title: 'Multilingual Intelligent Real-time Agent',
    dots: [
      dot({
        answer: 'Production voice AI',
        behaviors: ['pulse', 'condense'],
        body: 'Project name, one-line outcome and tech badges open the MIRA case study.',
        camera: 'Wide arrival on MIRA density node, center-right and slightly elevated.',
        id: 'hero',
        label: '1/7',
        question: 'What is the project?',
        tags: ['FASTAPI', 'PIPECAT', 'WEBSOCKETS'],
        title: 'MIRA',
        visual: 'Gold-white particles form MIRA above a compact voice-intake subtitle.',
      }),
      dot({
        answer: 'Manual qualification delay',
        behaviors: ['pulse', 'condense'],
        body: 'Manual SDR follow-ups on DriveX leads were slow and unscalable.',
        camera: 'Moves from the hero field toward the sales-operation bottleneck.',
        id: 'problem',
        label: '2/7',
        question: 'What bottleneck did operations have?',
        tags: ['LEAD INTAKE', 'SALES OPS', 'CRM'],
        title: 'Operational Problem',
        visual: 'Gold node pulses twice, then tightens without forming a full artifact.',
      }),
      dot({
        answer: 'WebSocket -> VAD -> ASR -> LLM',
        behaviors: ['route'],
        body: 'Full-duplex audio stream orchestration across multiple models.',
        camera: 'Moves closer with slight downward tilt to show arc contraction.',
        id: 'system',
        label: '3/7',
        question: 'How is the system built?',
        tags: ['VAD', 'ASR', 'TTS', 'LLM'],
        title: 'System I Built',
        visual: 'Long curved latency arcs contract into tight direct connection lines.',
      }),
      dot({
        answer: 'FastAPI, Redis, Kubernetes',
        behaviors: ['route'],
        body: 'Distributed, containerized services handle audio, intent, and sync.',
        camera: 'Rotates 30 degrees clockwise to reveal band depth and separation.',
        id: 'build',
        label: '4/7',
        question: 'What components run the pipeline?',
        tags: ['FASTAPI', 'REDIS', 'KUBERNETES'],
        title: 'Build',
        visual: 'Five colored orbital signal streams form around the MIRA core.',
      }),
      dot({
        answer: '7s -> <500ms TTFB',
        behaviors: ['route'],
        body: 'Pipelining ASR and LLM execution collapsed first-byte response time.',
        camera: 'Slightly above-left view frames the incoming stream and fork.',
        id: 'challenge',
        label: '5/7',
        question: 'What was the hardest engineering constraint?',
        tags: ['PIPECAT', 'STREAMING'],
        title: 'Hard Technical Challenge',
        visual: 'Incoming call particles fork into VAD, ASR, and language streams.',
      }),
      dot({
        answer: '68 Days, 5 Languages',
        behaviors: ['condense', 'pulse'],
        body: 'One core flow handles English, Hindi, Tamil, Kannada, and Telugu.',
        camera: 'Center-facing frame with routing core in focal center.',
        id: 'proof',
        label: '6/7',
        question: 'What proves it shipped?',
        tags: ['PRODUCTION', '68 DAYS', '5 LANGUAGES'],
        title: 'Proof of Execution',
        visual: 'Split streams converge into a dense core with pulsing handoff nodes.',
      }),
      dot({
        answer: 'Operational actions, not transcripts',
        behaviors: ['pulse', 'shear', 'rejoin'],
        body: 'CRM sync and WhatsApp automation turned calls into actionable workflows.',
        camera: 'Chapter climax, then travel toward AIDEN.',
        id: 'reflection',
        label: '7/7',
        question: 'What changed and what would improve next?',
        tags: ['OBSERVABILITY', 'REPLAY TESTS'],
        title: 'Reflection',
        visual: 'Entire artifact brightens, pulses from core, then dissolves last at bands.',
      }),
    ],
  }),
  chapter({
    catalogueLabel: 'AIDEN CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.AIDEN,
    complexity: 'high',
    dotCount: 6,
    id: 'AIDEN',
    mostDemandingDotId: 'diarization',
    particlePoolPercent: 12,
    title: 'AI-Driven ENgagement Analytics',
    dots: [
      dot({
        answer: 'Call intelligence',
        behaviors: ['condense', 'route'],
        body: 'Full-stack analytics platform for sales management call visibility.',
        camera: 'Side-elevation view with two bands running left to right.',
        id: 'speaker-separation',
        label: '1/6',
        question: 'What is AIDEN?',
        tags: ['REACT', 'DJANGO', 'KUBERNETES'],
        title: 'Speaker Separation',
        visual: 'Agent and customer particles separate into two horizontal bands.',
      }),
      dot({
        answer: 'Speaker diarization',
        behaviors: ['condense'],
        body: 'Every utterance attributed and every speaker separated across calls.',
        camera: 'Oblique 30 degree front view reveals helix depth.',
        id: 'diarization',
        label: '2/6',
        question: 'Can you tell them apart?',
        tags: ['DIARIZATION', 'TRANSCRIPTION', 'PARALINGUISTICS'],
        title: 'Diarization',
        visual: 'Two bands braid into a cyan and amber conversation helix.',
      }),
      dot({
        answer: '8 SOP dimensions',
        behaviors: ['pulse'],
        body: 'Greeting, discovery, pitch, objection handling, close, and compliance.',
        camera: 'Slight overhead tilt shows helix and all scoring planes.',
        id: 'sop-scoring',
        label: '3/6',
        question: 'How is quality measured?',
        tags: ['LLM SCORING', 'SOP', 'ANALYTICS'],
        title: 'SOP Scoring',
        visual: 'Eight semi-transparent scoring planes slice through the helix.',
      }),
      dot({
        answer: 'Parallel LLM analysis',
        behaviors: ['route'],
        body: 'Multiple models run across emotion, content, and SOP compliance.',
        camera: 'Pulls back to show helix plus three parallel tracks.',
        id: 'parallel-llm',
        label: '4/6',
        question: 'How deep is the analysis?',
        tags: ['PARALLEL LLM', 'HUME AI', 'STRUCTURED OUTPUTS'],
        title: 'Parallel LLM Tracks',
        visual: 'Three analysis tracks split from the helix and rejoin at insight nodes.',
      }),
      dot({
        answer: 'Zoho CRM embedded',
        behaviors: ['condense'],
        body: 'React dashboard embedded inside Zoho CRM for managers.',
        camera: 'Shifts right to frame helix, bridge, and dashboard grid.',
        id: 'dashboard-surface',
        label: '5/6',
        question: 'Where does it surface?',
        tags: ['REACT', 'ZOHO CRM', 'EMBEDDED'],
        title: 'Dashboard Surface',
        visual: 'Output particles organize into an angled layered dashboard grid.',
      }),
      dot({
        answer: 'K8s + E2E coverage',
        behaviors: ['condense', 'pulse', 'shear', 'rejoin'],
        body: 'Production Kubernetes deployment with full end-to-end test coverage.',
        camera: 'Wide hold before travel toward VANGUARD.',
        id: 'reliability',
        label: '6/6',
        question: 'Does it hold?',
        tags: ['KUBERNETES', 'PLAYWRIGHT', 'E2E'],
        title: 'Reliability',
        visual: 'Sparse green-gold guardrail encloses helix, tracks, and dashboard.',
      }),
    ],
  }),
];

export const SUPERCLUSTER_CHAPTERS: readonly SuperclusterChapter[] = [
  ...SUPERCLUSTER_HEAD_CHAPTERS,
  ...SUPERCLUSTER_TAIL_CHAPTERS,
  ...SUPERCLUSTER_FINAL_CHAPTERS,
];
