import { SUPERCLUSTER_CHAPTER_COLORS } from './constants';
import type { SuperclusterChapter, SuperclusterDot } from './types';

function dot(config: SuperclusterDot): SuperclusterDot {
  return config;
}

function chapter(config: SuperclusterChapter): SuperclusterChapter {
  if (config.dots.length !== config.dotCount) {
    throw new Error(`Dot count mismatch for ${config.id}`);
  }
  return config;
}

export const SUPERCLUSTER_FINAL_CHAPTERS: readonly SuperclusterChapter[] = [
  chapter({
    catalogueLabel: 'WAVEFIELD CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.WAVEFIELD,
    complexity: 'very-high',
    dotCount: 5,
    id: 'WAVEFIELD',
    mostDemandingDotId: 'wave-transform',
    particlePoolPercent: 18,
    title: 'Sub-Quadratic Attention Mechanism Research',
    dots: [
      dot({
        answer: 'O(n^2) attention',
        behaviors: ['condense'],
        body: 'Standard transformer attention becomes impossible at 1M tokens.',
        camera: 'Top-down with slight forward tilt; triangular matrix fills frame.',
        id: 'attention-wall',
        label: '1/5',
        question: "What's the problem?",
        tags: ['TRANSFORMER', 'ATTENTION', 'COMPLEXITY'],
        title: 'Attention Wall',
        visual: 'A triangular matrix fills with dense violet pairwise filaments.',
      }),
      dot({
        answer: 'Wave field decomposition',
        behaviors: ['shear', 'condense'],
        body: "Fourier wave functions and Green's function paths replace pairwise dots.",
        camera: 'Tilts from overhead to 45 degrees as the wave surface forms.',
        id: 'wave-transform',
        label: '2/5',
        question: "What's the approach?",
        tags: ['FOURIER', 'GREEN FUNCTION', 'WAVE FIELD'],
        title: 'Wave Transform',
        visual: 'Dense matrix dissolves into a three-dimensional wave surface.',
      }),
      dot({
        answer: 'Content-dependent gating',
        behaviors: ['pulse'],
        body: 'Relevant tokens remain active without computing all pairs.',
        camera: 'Static 45 degree angle shows gates across full wave width.',
        id: 'content-gates',
        label: '3/5',
        question: 'How does it stay selective?',
        tags: ['GATING', 'SELECTIVE ATTENTION', 'KERNEL'],
        title: 'Content Gates',
        visual: 'Vertical gates open and close across the wave surface.',
      }),
      dot({
        answer: 'O(n log n)',
        behaviors: ['route'],
        body: 'The route targets massive theoretical speedup at 1M tokens.',
        camera: 'Moves alongside the route line from left to right.',
        id: 'complexity-compression',
        label: '4/5',
        question: "What's the result?",
        tags: ['O(N LOG N)', 'ALMAN-YU', 'ICLR 2025'],
        title: 'Complexity Compression',
        visual: 'A bright path travels along the wave crest beside matrix ghosting.',
      }),
      dot({
        answer: 'Complete research paper',
        behaviors: ['pulse', 'shear', 'rejoin'],
        body: 'Derived mechanism, theoretical grounding, complexity proof, and paper.',
        camera: 'Holds final research diagram before travel to EMI.',
        id: 'research-framework',
        label: '5/5',
        question: "What's the deliverable?",
        tags: ['RESEARCH', 'THEORY', 'PAPER'],
        title: 'Research Framework',
        visual: 'Proof points brighten at gates, crest route, Fourier bands, and boundaries.',
      }),
    ],
  }),
  chapter({
    catalogueLabel: 'EMI CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.EMI,
    complexity: 'medium',
    dotCount: 5,
    id: 'EMI',
    mostDemandingDotId: 'frequency-sweep',
    particlePoolPercent: 10,
    title: 'Electromagnetic Interference Shielding Simulator',
    dots: [
      dot({
        answer: 'Multi-phase shielding',
        behaviors: ['condense'],
        body: 'Composite EMI shielding simulation across multiple material layers.',
        camera: 'Side elevation with slight height on concentric cross-section.',
        id: 'material-layers',
        label: '1/5',
        question: "What's being modelled?",
        tags: ['EM SHIELDING', 'COMPOSITE', 'SIMULATION'],
        title: 'Material Layers',
        visual: 'A half-pipe cross-section builds concentric layers inside-out.',
      }),
      dot({
        answer: '100 kHz to 10 GHz',
        behaviors: ['route'],
        body: 'Full frequency sweep across the material cross-section.',
        camera: 'Side elevation tracks the attenuating wavefront left to right.',
        id: 'frequency-sweep',
        label: '2/5',
        question: "What's the test range?",
        tags: ['FREQUENCY SWEEP', '100KHZ', '10GHZ'],
        title: 'Frequency Sweep',
        visual: 'Wavefront scatters, absorbs, and transmits through material layers.',
      }),
      dot({
        answer: 'Reflection + Absorption + SE',
        behaviors: ['condense'],
        body: 'Three separated output terms measure shielding effectiveness.',
        camera: 'Shifts right to frame output curves beside the cross-section.',
        id: 'output-curves',
        label: '3/5',
        question: 'What does it measure?',
        tags: ['SHIELDING EFFECTIVENESS', 'DB', 'SCHELKUNOFF'],
        title: 'Output Curves',
        visual: 'Exit particles organize into reflection, absorption, and total SE curves.',
      }),
      dot({
        answer: 'Real microstructure',
        behaviors: ['pulse', 'route'],
        body: 'Composite material composition is modelled at microstructure level.',
        camera: 'Pushes into one layer, then pulls back to full system response.',
        id: 'microstructure',
        label: '4/5',
        question: 'What makes it accurate?',
        tags: ['MICROSTRUCTURE', 'COMPOSITE', 'VECTORIZED'],
        title: 'Microstructure',
        visual: 'Irregular grain clusters pulse and shift the output curves.',
      }),
      dot({
        answer: 'Validation envelope',
        behaviors: ['condense', 'shear', 'rejoin'],
        body: 'Frequency-dependent shielding bounds with service-life prediction.',
        camera: 'Holds envelope around curves before travel to FORMULA.',
        id: 'validation-envelope',
        label: '5/5',
        question: "What's the deliverable?",
        tags: ['VALIDATION', 'SERVICE LIFE', 'JENKINS'],
        title: 'Validation Envelope',
        visual: 'Upper and lower particle bounds wrap the output curves.',
      }),
    ],
  }),
  chapter({
    catalogueLabel: 'FORMULA CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.FORMULA,
    complexity: 'medium',
    dotCount: 5,
    id: 'FORMULA',
    mostDemandingDotId: 'operations-network',
    particlePoolPercent: 12,
    title: 'Formula Manipal Race Operations',
    dots: [
      dot({
        answer: 'Formula Manipal',
        behaviors: ['route'],
        body: 'Operations Lead for the FM23e electric race car at Formula Bharat 2024.',
        camera: 'High top-down, slow clockwise rotation over the full circuit.',
        id: 'track-path',
        label: '1/5',
        question: "What's the context?",
        tags: ['FORMULA BHARAT', 'EV', 'AUTONOMOUS'],
        title: 'Track Path',
        visual: 'A red circuit filament traces straights, hairpins, chicanes, and pit lane.',
      }),
      dot({
        answer: 'Live telemetry',
        behaviors: ['route'],
        body: 'Track-side testing data drove path planning improvements.',
        camera: 'Lowers to 40 degree perspective over circuit and telemetry ribbon.',
        id: 'telemetry-stream',
        label: '2/5',
        question: 'What did the car produce?',
        tags: ['TELEMETRY', 'PATH PLANNING', 'TRACK-SIDE'],
        title: 'Telemetry Stream',
        visual: 'Vehicle particle laps with speed, braking, and apex telemetry trail.',
      }),
      dot({
        answer: '40% control accuracy',
        behaviors: ['pulse'],
        body: 'Autonomous path planning improvements validated through track testing.',
        camera: 'Tracks low through corners showing original and improved line gap.',
        id: 'racing-line',
        label: '3/5',
        question: 'What improved?',
        tags: ['PATH PLANNING', 'AUTONOMOUS', '40% IMPROVEMENT'],
        title: 'Racing Line',
        visual: 'Gold improved line brightens over dim blue original at each apex.',
      }),
      dot({
        answer: 'INR 60L in sponsorships',
        behaviors: ['route'],
        body: 'Operations leadership across engineering, strategy, sponsorship, and logistics.',
        camera: 'Wide top-down frames track, car, telemetry, and operations nodes.',
        id: 'operations-network',
        label: '4/5',
        question: 'What else?',
        tags: ['OPERATIONS', 'SPONSORSHIP', 'MANUFACTURING'],
        title: 'Operations Network',
        visual: 'Six operation clusters connect around the track and moving car.',
      }),
      dot({
        answer: '1st place, Cost & Manufacturing',
        behaviors: ['pulse', 'shear', 'rejoin'],
        body: 'Formula Bharat 2024 delivery across planning, testing, and operations.',
        camera: 'Holds final constellation before widest final portfolio shear.',
        id: 'competition-constellation',
        label: '5/5',
        question: "What's the result?",
        tags: ['FORMULA BHARAT 2024', '1ST PLACE', 'DELIVERED'],
        title: 'Competition Constellation',
        visual: 'Track, car, telemetry, lines, nodes, and filaments pulse together.',
      }),
    ],
  }),
];
