import { SUPERCLUSTER_CHAPTER_COLORS } from './constants';
import type { SuperclusterChapter, SuperclusterDot } from './types';

function dot(config: SuperclusterDot): SuperclusterDot {
  return config;
}

function chapter(config: SuperclusterChapter): SuperclusterChapter {
  if (config.dots.length !== config.dotCount) {
    throw new Error(`Dot count mismatch for ${config.id}`);
  }
  return config;
}

export const SUPERCLUSTER_TAIL_CHAPTERS: readonly SuperclusterChapter[] = [
  chapter({
    catalogueLabel: 'VANGUARD CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.VANGUARD,
    complexity: 'medium',
    dotCount: 5,
    id: 'VANGUARD',
    mostDemandingDotId: 'fail-reroute',
    particlePoolPercent: 10,
    title: 'Autonomous Web Testing Agent',
    dots: [
      dot({
        answer: 'Autonomous web testing',
        behaviors: ['condense'],
        body: 'Validates the DriveX corporate website end-to-end without scripted tests.',
        camera: 'Isometric elevated angle shows the full directed browser graph.',
        id: 'browser-graph',
        label: '1/5',
        question: 'What does Vanguard do?',
        tags: ['VLM', 'PLAYWRIGHT', 'AUTONOMOUS'],
        title: 'Browser Graph',
        visual: 'Browser states condense into compact nodes with directional edges.',
      }),
      dot({
        answer: 'VLM + Playwright',
        behaviors: ['route'],
        body: 'A local vision model observes page state and decides the next action.',
        camera: 'Medium tracking drift follows the probe through the graph.',
        id: 'agent-probe',
        label: '2/5',
        question: 'How does it test?',
        tags: ['VLM', 'PLAYWRIGHT', 'AGENTIC'],
        title: 'Agent Probe',
        visual: 'A bright probe traverses graph paths and leaves a luminous trail.',
      }),
      dot({
        answer: 'Reroute and document',
        behaviors: ['pulse', 'route'],
        body: 'Failed paths are logged red-violet and alternate routes glow green.',
        camera: 'Pushes in on failure flash, then tracks the alternate route.',
        id: 'fail-reroute',
        label: '3/5',
        question: 'What happens when it fails?',
        tags: ['FAILURE DETECTION', 'RETRY LOGIC', 'LOGGING'],
        title: 'Fail and Reroute',
        visual: 'Failed nodes stay red-violet while the successful reroute turns green.',
      }),
      dot({
        answer: 'DOM + screenshot',
        behaviors: ['condense'],
        body: 'The agent reads both structural state and visual state simultaneously.',
        camera: 'Pushes into one node, then pulls back to show the layered graph.',
        id: 'dom-diagnostic',
        label: '4/5',
        question: 'What does it see?',
        tags: ['DOM INSPECTION', 'VISUAL DIFF', 'PLAYWRIGHT'],
        title: 'DOM Diagnostic',
        visual: 'Nodes reveal DOM sub-lattices and reclined screenshot backing planes.',
      }),
      dot({
        answer: 'Release confidence',
        behaviors: ['pulse', 'shear', 'rejoin'],
        body: 'A continuous risk signal across the full site, not a pass/fail checklist.',
        camera: 'Holds complete risk portrait before travel to INSPECTION.',
        id: 'release-risk-map',
        label: '5/5',
        question: "What's the output?",
        tags: ['RISK SIGNAL', 'CONTINUOUS QA'],
        title: 'Release Risk Map',
        visual: 'Graph shifts into green, amber, and red-violet risk temperature.',
      }),
    ],
  }),
  chapter({
    catalogueLabel: 'INSPECTION CATALOGUE',
    colors: SUPERCLUSTER_CHAPTER_COLORS.INSPECTION,
    complexity: 'medium',
    dotCount: 5,
    id: 'INSPECTION',
    mostDemandingDotId: 'silhouette',
    particlePoolPercent: 8,
    title: 'AI-Powered Vehicle Inspection System',
    dots: [
      dot({
        answer: '1,000+ vehicle parts',
        behaviors: ['carve'],
        body: 'AI-powered inspection of two-wheeler vehicles across parts inventory.',
        camera: '3/4 front angle, medium distance, centered vehicle silhouette.',
        id: 'silhouette',
        label: '1/5',
        question: 'What does it inspect?',
        tags: ['YOLOV8', 'COMPUTER VISION', 'ELECTRON'],
        title: 'Silhouette',
        visual: 'Particles carve a two-wheeler boundary while the interior stays void.',
      }),
      dot({
        answer: 'YOLOv8 detection',
        behaviors: ['route', 'pulse'],
        body: 'Inference runs across live RTSP camera feeds from inspection stations.',
        camera: 'Holds 3/4 angle with slight clockwise rotation during sweep.',
        id: 'camera-sweep',
        label: '2/5',
        question: 'How does it find defects?',
        tags: ['YOLOV8', 'RTSP', 'REAL-TIME'],
        title: 'Camera Sweep',
        visual: 'Four scan rays sweep the vehicle and hold orange defect heat zones.',
      }),
      dot({
        answer: 'Live RTSP feeds',
        behaviors: ['route'],
        body: 'Real-time camera streams from physical inspection stations.',
        camera: 'Pulls back to show vehicle and asynchronous stream bands.',
        id: 'live-streams',
        label: '3/5',
        question: "What's the source?",
        tags: ['RTSP', 'SHOWROOM', 'REAL-TIME'],
        title: 'Live Streams',
        visual: 'Four background bands move left to right behind the vehicle.',
      }),
      dot({
        answer: 'Electron desktop app',
        behaviors: ['condense'],
        body: 'Inspection tool with feed monitoring, reports, and part-level history.',
        camera: 'Shifts right to frame vehicle and two output surfaces.',
        id: 'operations-output',
        label: '4/5',
        question: 'Where does it run?',
        tags: ['ELECTRON', 'REACT', 'STRAPI'],
        title: 'Operations Output',
        visual: 'Defect particles organize into desktop and report panel grids.',
      }),
      dot({
        answer: 'Structured evidence',
        behaviors: ['route', 'shear', 'rejoin'],
        body: 'Consistent inspection report with defect location and severity.',
        camera: 'Report column exits downward-right before travel to WAVEFIELD.',
        id: 'inspection-report',
        label: '5/5',
        question: "What's the output?",
        tags: ['REPORT', 'CONSISTENT', 'STRUCTURED'],
        title: 'Inspection Report',
        visual: 'Ordered defect groups depart in line-item report formation.',
      }),
    ],
  }),
];
